name: social_media_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  linkfy_text: ^1.1.6
  smooth_page_indicator: ^1.2.0+3
  story_time: ^1.0.6
  font_awesome_flutter: ^10.7.0
  flutter_fancy_tree_view: ^1.6.0
  flutter_reaction_button: ^3.0.0+3
  get: ^4.6.6
  dio: ^5.7.0
  intl: ^0.19.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  hive_generator: ^2.0.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.4.0


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Glory
      fonts:
        - asset: assets/fonts/Glory-Bold.ttf
          weight: 700
        - asset: assets/fonts/Glory-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Glory-Medium.ttf
          weight: 500
        - asset: assets/fonts/Glory-Regular.ttf
          weight: 400
        - asset: assets/fonts/Glory-LIGHT.ttf
          weight: 300

